### ISSUE TITLE
read_loglikelihood syntax issue

### ISSUE THREAD

**Issue by alexandregilardet** [StephanePeyregne/AuthentiCT#1]
Hi,

I'm trying to setup AuthentiCT. I've created a conda environment with python 3.6 to install it via pip3 and successfully managed but when running:
`./AuthentiCT.py deam2cont -o test -s 10000 test_dataset/Sima.incisor.subset_test.sam`
I get the following error:
```
Traceback (most recent call last):
  File "./AuthentiCT.py", line 3, in <module>
    from AuthentiCT.cli import main
  File "alexandre/AuthentiCT/AuthentiCT/cli.py", line 16, in <module>
    from .contamination_est import compute_loglikelihood, format_loglikelihood
  File "alexandre/AuthentiCT/AuthentiCT/contamination_est.py", line 104
    cpdef read_loglikelihood(object read, double e, double rss, double p, double s, double d, double rds, double contam, double o, double o2, vector[double] match, vector[double] deam, vector[double] error, bint maximize=True):
                           ^
SyntaxError: invalid syntax
```
I'm worried that the program didn't compile properly as I had to manually correct:
`AuthentiCT/contamination_est.pyx` to `AuthentiCT/contamination_est.py`
And `from libcpp.vector cimport vector` to `from libcpp.vector import vector` in `contamination_est.py`

Thanks for the help!
Alexandre

**Comment by StephanePeyregne** [comment]
Hi Alexandre,
My apology for answering so late. Did you try to run the installed version of AuthentiCT instead of running it from the current directory with "./"? The installation should be handled by setup.py, you should not need to change the code or install dependencies manually: did you get an error when running "pip3 install ." from the AuthentiCT directory after cloning the repository in the conda environment?
Please let me know.
Cheers,
Stéphane

**Comment by alexandregilardet** [comment]
Hi Stéphane,
Calling the installed version solved my issues, thanks for the help!
